### ISSUE TITLE
[첫 회의] 파싱작업 목록

### ISSUE THREAD

**Issue by hey-chocopie** [Webserv-V1/Webserv#4]
# 1. 파싱
### 0. conf file
* nginx, conf 기능중에서 webserv에 사용할 기능 정리. 

### 1. 메소드 구현
* 실제 클라이언트에서 파일 보내는 값 받을수 잇으면 받아보기. 
* You need at least GET, POST, and DELETE methods.

### 2. 헤드
* 특징 파악하기.

### 3. 본문 
일단 미루자.

**Comment by sejinpark12** [comment]
화이팅~!🧑‍💻

**Comment by hey-chocopie** [comment]
감사합니다🤠
